### ISSUE TITLE
Number of tracks from DS 89 vs 91 if DS ist deactivated

### ISSUE THREAD

**Issue by eckhchri** [eckhchri/pcars-ds-liveview#26]
Different number of tracks within the TrackList table.

If DS is runnung ( even no race/practice was startet) we have 89 tracks
If DS is disabled we have 91 tracks

**Comment by viper4gh** [comment]
How are the 91 tracks counted?
Because we have 2 default tracks with the IDs 8888888888 and 999999999.

**Comment by viper4gh** [comment]
grep aRef class_reference_points.js | grep -v Array | grep -v circuit | grep -v console | grep -v return | wc -l
results in 91
We have 91 refPoints in the class_reference_points.js
The first 2 points are default refPoints to inherit values to track refPoints, but they are no tracks.
I think all is correct, because we have 89 track refPoints in the class_reference_points.js.

**Comment by eckhchri** [comment]
Change way of implementation for BuildTracklist(). Now this function will merge RefPointTracklist with DSTracklist to create a unioin of both.
